### ISSUE TITLE
Comparing similar strings

### ISSUE THREAD

**Issue by Maximres** [Dirkster99/Aehnlich#5]
Hi,
It's not exactly a bug, but enhancement. Is it possible to group similar lines and compare them? As you can see on screenshot, lines #21 are compared, however, lines #21 and #22 have a more suitable format for comparison. The line number 21 on the right should be marked as added, and the subsequent lines should be compared, because they start with the same values

![image](https://user-images.githubusercontent.com/31441331/57049928-c64d1700-6c82-11e9-9478-c13c42da8d6d.png)

**Comment by Dirkster99** [comment]
Hi, can you please attach original/text sample files that can be used to generate this screenshot? Otherwise, its really difficult (for organizational reasons) to look into this. Thanks

**Comment by Maximres** [comment]
[3.1.txt](https://github.com/Dirkster99/Aehnlich/files/3137927/3.1.txt)
[3.2.txt](https://github.com/Dirkster99/Aehnlich/files/3137928/3.2.txt)

**Comment by Dirkster99** [comment]
The TextDiff is computed in [AehnlichLib.Text.TextDiff.Execute(IList<string> listA, IList<string> listB)](https://github.com/Dirkster99/Aehnlich/blob/master/source/AehnlichLib/Text/TextDiff.cs#L75)

The 'problem' you are reporting is not a bug at all. The current algorithm simply does not look at the next or previous line to determine if there is a better match to be had or not :-(

The problem you are seeing is evolving in line 21 - this line has 2 common letters '12' which is good enough for the algorithm to assume a similarity:
![Untitled1](https://user-images.githubusercontent.com/2129700/57161642-58bcfa00-6dec-11e9-8436-466e7488676f.png)

Now, there are a number of ways to improve this.
1) You could try looking one line below or up to see if there is a better match and try to aline that inserting an imaginary line instead
![Untitled](https://user-images.githubusercontent.com/2129700/57161808-c5d08f80-6dec-11e9-9228-fb2b4519fa23.png)

2) Or you could define a threshold to define the minimum number of letters where you could assume a similarity - in this example you might say 2 letters out of 10 is still not similar (and you would be right). The algorithm could then recognize this as being dissimilar and attempt to align by inserting imaginary lines ...

3) I could also make both text editable such that someone who wants a different alignment can insert there imaginary lines manually and then align lines again from there ...

Right, now I don't think I am anywhere near any of these solutions as I am realy busy rebuilding the original .Net app using WPF. But I'd realy like the idea and would like to look into improving the alignments if thats reasonable and possible.

So, I might be looking into this but it could be a few weeks or months until I am able to do something about it. Maybe you can analyse the code I've referenced and make a more qualified suggestions with a pull-request or branch to look at?

**Comment by Dirkster99** [comment]
Hi,

I've added an editor feature (is still alpha but stable enough - saving edited changes is not implemented, yet). This feature should be interesting for this issue because editing text to realign missaligned content should be helpful to resolve miss-aligned lines. Would you be able to test this and give me your feedback please?

![Untitled1](https://user-images.githubusercontent.com/2129700/84326449-32d06000-ab7d-11ea-9f99-d05412f9ee5c.png)
