### ISSUE TITLE
Left selection border

### ISSUE THREAD

**Issue by softworkz** [Dirkster99/Aehnlich#7]
Once again: great library. It's a shame that I'm the only fork at this time.

Maybe you'd need some more appealing screenshots... :-)

![image](https://user-images.githubusercontent.com/4985349/66007683-a7fa7a00-e4b3-11e9-9e06-3c31ef473379.png)

I'm wondering whether you could help me with one issue:

I like the rounded selection borders, but the borders always get clipped on the left edge, as there's one or two pixels missing for painting it properly.

Do you have any idea how this could be achieved?

**Comment by Dirkster99** [comment]
Hi, thanks for your good feedback - I'll update those screenshots when time permits it...

I don't really know the solution to the rounded selection corner problem - :-( but this is a good question to raise at the [AvalonEdit ](https://github.com/icsharpcode/AvalonEdit) project and folks are usually quick to help (my guess is a problem in AvalonEdit's template but I really don't know a solution off hand). Please try to resolve this with the AvalonEdit project.

Thank you.

**Comment by softworkz** [comment]
Thanks a lot for your reply!

**Comment by softworkz** [comment]
For reference: https://github.com/icsharpcode/AvalonEdit/issues/199
