### ISSUE TITLE
Live Editing

### ISSUE THREAD

**Issue by softworkz** [Dirkster99/Aehnlich#8]
One more question: Have you ever tried to get the diff feature working with editing allowed?
Like - did it turn out to be tough to get it working or is it just that you have never tried because you never needed it?

**Comment by Dirkster99** [comment]
I never tried but consider it tough. Am currently thinking about adding a feature for diffing text without requiring it to be a saved document. For this. my initial intention is to use the same Editing/Diff mode feature as in the [original application](https://github.com/Dirkster99/Aehnlich/wiki/Diff.Net).

Would you have any idea about implementing a Live Editing feature? Maybe we can can pull this stunt together?

**Comment by softworkz** [comment]
Unfortunately, the diffing feature is just a sub-sub-sub-side detail of the work I'm currently doing and I can't afford spending more than very little time on this right now.
The primary reason why I asked was not even aiming for allowing full-fledged editing - it's more about being able to "fix" the diff results every now and then.

The employed Myer's diff algorithm is pretty good and when I compare the diff results with other products - e.g. dev art code compare - the results are between similar to almost identical.

But when the compared content is not adhering to patterns that are easy to identify - e.g. log files instead of source code files - even the best diff algorithm can easily loose sync between left and right.

By deleting (or adding) one or another line at the left or right side, it's often possible to get both sides back in sync and proceed to the actual point of interest..

Yet, not a top priority right now, but I'll let you know when I got some time to get into this!

**Comment by Dirkster99** [comment]
OK, right now I am also aiming to get this feature complete in comparison to the original Windows Forms project which means I'll add editing/compare modes such that we are able to update ,ore frequently with editing but do not have to change the program (just click toggle button from compare to edit, edit, click toggle button from edit to compare etc.. is what I am looking to get into the first version - from there we can look at more intuitive things like live editing features...

**Comment by softworkz** [comment]
That sounds great! I'm looking forward to trying..

**Comment by Dirkster99** [comment]
I've started to support editing - saving changed data is still to come - but you can already play with the editing/(re-)comparing alpha feature - what do you think about it?

![Untitled1](https://user-images.githubusercontent.com/2129700/84326635-b12d0200-ab7d-11ea-8022-a0a3a642276c.png)

**Comment by softworkz** [comment]
I'm interested, but why are there two modes?

**Comment by Dirkster99** [comment]
I am not sure what you mean - its currently not possible to show an updated comparison during text editing (it simply takes too long for long files). So, as I previously explained, editing and updating the comparison results when uodating is done is currently the best I can do here...

**Comment by softworkz** [comment]
That doesn't help in my case.

The primary reason why I want to update is for being able to add some line breaks left and right in order to "help" the algorithm to compare the right text blocks.

In such cases I'm currently switching to Devart CodeCompare which seems to use the same algorithm (results are often identical) but in some optimized way, especially when left or right side is being changed.

If that would be part of my primary work, you would already see PRs for this. I hope I will find some time eventually..
